# Generated by Django 5.1.5 on 2025-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='administrator',
            name='contact_number',
            field=models.CharField(default='0700000000', help_text='Phone number for contact', max_length=20),
        ),
    ]
