# Generated by Django 5.1.8 on 2025-04-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reported_date',
            field=models.DateTimeField(),
        ),
    ]
