# Generated by Django 5.1.5 on 2025-05-21 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_issue_assigned_to_issue_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status_name'], 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='issue',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or notes about this status', null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Pending Information', 'Pending Information')], default='Open', max_length=50),
        ),
    ]
