# Generated by Django 5.1.5 on 2025-05-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_remove_administrator_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='course_units',
        ),
    ]
