# Generated by Django 5.2 on 2025-04-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_user_name_userrole_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
