# Generated by Django 5.1.5 on 2025-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='session_time',
            field=models.DateTimeField(),
        ),
    ]
