# Generated by Django 5.1.5 on 2025-04-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0003_alter_loginhistory_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='default_course', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default='default_registration_number', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default='default_student_number', max_length=50, unique=True),
        ),
    ]
