# Generated by Django 5.2 on 2025-04-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0004_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='lecturer',
            new_name='assigned_to',
        ),
    ]
