# Generated by Django 5.2 on 2025-04-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0005_alter_issue_assigned_to_alter_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
