# Generated by Django 5.1.5 on 2025-05-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0006_remove_issue_assigned_to_remove_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='student',
        ),
    ]
