from django.urls import path,include
from rest_framework.routers import DefaultRouter
from .views import (
    LoginHistoryViewSet,
    StudentViewSet,
    AdministratorViewSet,
    LecturerViewSet,
    IssueViewSet,
    NotificationViewSet,
    StatusViewSet,
    UserRoleViewSet,
    UserRegistrationView,
)

#DefaultRouter is a feacture in Django REST Framework that automatically generates URL patterns for your API ViewSets
#Create a router object
router = DefaultRouter()
router.register(r'Student',StudentViewSet)
router.register(r'Administrator',AdministratorViewSet)
router.register(r'Lecturer',LecturerViewSet)
router.register(r'Issue',IssueViewSet)
router.register(r'Notification',NotificationViewSet)
router.register(r'Status',StatusViewSet)
router.register(r'LoginHistory',LoginHistoryViewSet)
router.register(r'UserRole',UserRoleViewSet)
router.register(r'register',UserRegistrationView, basename='register')



# It include all routs generated by the router
urlpatterns = [
    path('api/', include(router.urls)),
    path('register/', UserRegistrationView.as_view(), name = 'user-register'),
    path('login/', LoginHistoryViewSet.as_view({'post': 'create'}))
]



