from django.urls import path,include
from rest_framework.routers import DefaultRouter
from .views import (
    LoginHistoryViewSet,
    StudentViewSet,
    AdministratorViewSet,
    LecturerViewSet,
    IssueViewSet,
    NotificationViewSet,
    StatusViewSet,
    UserRoleViewSet,
    UserRegistrationView,
    filter_issues,
    user_login, 
)

#DefaultRouter is a feacture in Django REST Framework that automatically generates URL patterns for your API ViewSets
#Create a router object
router = DefaultRouter()
router.register(r'student',StudentViewSet, basename = 'student')
router.register(r'administrator',AdministratorViewSet, basename = 'administrator')
router.register(r'Lecturer',LecturerViewSet, basename = 'Lecturer')
router.register(r'Issue',IssueViewSet, basename = 'Issue')
router.register(r'Notification',NotificationViewSet, basename = 'Notification')
router.register(r'Status',StatusViewSet, basename = 'Status')
router.register(r'LoginHistory',LoginHistoryViewSet, basename = 'LoginHistory')
router.register(r'UserRole',UserRoleViewSet, basename = 'UserRole')
router.register(r'UserRole',UserRegistrationView, basename = 'UserRole')



# It include all routs generated by the router
urlpatterns = [
    path('api', include(router.urls)),
    path('api/auth/register/', UserRegistrationView,  name = 'user-register'),
    path('api/auth/login-history/', LoginHistoryViewSet.as_view({'post': 'create'})),
    path('api/issues/filter/', filter_issues, name='filter-issues'),
    path('auth/login/', user_login, name='login'),
]




